language: python
install:
  - pip install -r requirements.txt
script:
  - python -m unittest
addons:
  sonarcloud:
    organization: "isbo-05-16"
script:
  - sonar-scanner
  - python -m coverage run -m unittest
after_success:
  coveralls
